version: '3.8'

services:
  web:
    build:
      context: .
      target: base
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_PATH: "/usr/local/bundle"
      BUNDLE_WITHOUT: "production"
      EMAIL: 'hollowtechsolutions@gmail.com'
      PASSWORD: 'Drako@391'
      SENDGRID_API_KEY: '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'
    volumes:
      - .:/rails
    depends_on:
      - db
    # Ensure the Rails server is running
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: "ruby:3.2.2-slim"
    command: /bin/true
    volumes:
      - ./db:/rails/db
